In [1]:
import pandas as pd

df = pd.read_csv("../data/jobs.csv")

In [2]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [3]:
df.columns

Index(['Job Title', 'Job Description'], dtype='object')

In [4]:
df.isnull().sum()

Job Title          0
Job Description    0
dtype: int64

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.shape

(2277, 2)

In [7]:
df["clean_text"] = df["Job Description"]

In [8]:
df["clean_text"] = df["clean_text"].str.lower()

In [9]:
import re

df["clean_text"] = df["clean_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+", "", str(x))
)

In [10]:
df["clean_text"] = df["clean_text"].apply(
    lambda x: re.sub(r"[^a-zA-Z\s]", " ", str(x))
)

In [11]:
df["clean_text"] = df["clean_text"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

In [12]:
df[["Job Title", "clean_text"]].head()

              Job Title                                         clean_text
0     Flutter Developer  we are looking for hire experts flutter develo...
1      Django Developer  python django developer lead job code pdj stro...
2      Machine Learning  data scientist contractor bangalore in respons...
3         iOS Developer  job description strong framework outside of io...
4  Full Stack Developer  job responsibility full stack engineer react r...

In [13]:
df.shape

(2277, 3)

In [14]:
df[["Job Title", "clean_text"]].head()

              Job Title                                         clean_text
0     Flutter Developer  we are looking for hire experts flutter develo...
1      Django Developer  python django developer lead job code pdj stro...
2      Machine Learning  data scientist contractor bangalore in respons...
3         iOS Developer  job description strong framework outside of io...
4  Full Stack Developer  job responsibility full stack engineer react r...

In [15]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in /home/intellact/.local/lib/python3.8/site-packages (3.9.1)
Requirement already satisfied: click in /home/intellact/.local/lib/python3.8/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /home/intellact/.local/lib/python3.8/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /home/intellact/.local/lib/python3.8/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /home/intellact/.local/lib/python3.8/site-packages (from nltk) (4.67.3)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to /home/intellact/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/intellact/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/intellact/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/intellact/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [18]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [19]:
def preprocess_text(text):

    words = text.split()

    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [20]:
df["processed_text"] = df["clean_text"].apply(preprocess_text)

In [21]:
df[["clean_text", "processed_text"]].head()

,clean_text,processed_text
0,we are looking for hire experts flutter develo...,looking hire expert flutter developer eligible...
1,python django developer lead job code pdj stro...,python django developer lead job code pdj stro...
2,data scientist contractor bangalore in respons...,data scientist contractor bangalore responsibi...
3,job description strong framework outside of io...,job description strong framework outside io al...
4,job responsibility full stack engineer react r...,job responsibility full stack engineer react r...

In [44]:
skills = [
    "python",
    "java",
    "c++",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "html",
    "css",
    "javascript",
    "react",
    "angular",
    "nodejs",
    "django",
    "flask",
    "spring",
    "machine learning",
    "deep learning",
    "nlp",
    "tensorflow",
    "pytorch",
    "pandas",
    "numpy",
    "scikit learn",
    "data analysis",
    "data science",
    "statistics",
    "power bi",
    "tableau",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "git",
    "linux",
    "flutter",
    "dart",
    "swift",
    "kotlin",
    "android",
    "ios",
    "firebase",
    "php",
    "laravel",
    "wordpress",
    "oracle",
    "hadoop",
    "spark",
    "excel",
    "jira",
    "rest api",
    "graphql",
    "microservices"
]

In [45]:
import re

def extract_skills(text):

    found_skills = []

    for skill in skills:

        pattern = r'\b' + re.escape(skill) + r'\b'

        if re.search(pattern, text):
            found_skills.append(skill)

    return found_skills

In [46]:
df["combined_text"] = (
    df["Job Title"].str.lower()
    + " "
    + df["processed_text"]
)

In [47]:
df["skills"] = df["combined_text"].apply(extract_skills)

In [48]:
df[["Job Title", "skills"]].head(10)

              Job Title                                             skills
0     Flutter Developer                                          [flutter]
1      Django Developer                [python, sql, django, flask, linux]
2      Machine Learning  [python, java, machine learning, deep learning...
3         iOS Developer                                              [ios]
4  Full Stack Developer                 [html, javascript, react, angular]
5        Java Developer                                [java, mysql, html]
6  Full Stack Developer  [java, mongodb, html, javascript, react, angul...
7  JavaScript Developer         [html, javascript, nodejs, azure, graphql]
8       DevOps Engineer                 [python, java, linux, php, hadoop]
9     Software Engineer                     [python, git, linux, rest api]

In [49]:
df["skills"].head()

0                                            [flutter]
1                  [python, sql, django, flask, linux]
2    [python, java, machine learning, deep learning...
3                                                [ios]
4                   [html, javascript, react, angular]
Name: skills, dtype: object

In [50]:
df["skills"].apply(len).describe()

count    2277.000000
mean        4.141414
std         2.793136
min         0.000000
25%         2.000000
50%         4.000000
75%         6.000000
max        16.000000
Name: skills, dtype: float64

In [51]:
df[df["Job Title"]=="Flutter Developer"][["Job Title","skills"]].head()

            Job Title                                         skills
0   Flutter Developer                                      [flutter]
45  Flutter Developer  [java, html, javascript, react, flutter, php]
50  Flutter Developer                                      [flutter]
65  Flutter Developer  [sql, javascript, flutter, android, firebase]
70  Flutter Developer                             [flutter, android]

In [52]:
df[df["Job Title"]=="Flutter Developer"].shape

(155, 6)

In [53]:
df[df["Job Title"]=="Flutter Developer"]["combined_text"].iloc[1]

'flutter developer looking experienced well knowledge react native flutter candidate please apply fresher basic knowledge skill developer responsibility build pixel perfect smooth uis across mobile platform develop new component feature mobile app diagnose fix bug performance bottleneck performance feel native requirement experience working javascript framework preferably react react native flutter firm grasp synchronous asynchronous javascript nuance including e syntax understanding flexbox based mobile ui design knowledge react native flutter approach towards component based structuring understanding rest apis rd party apis document request model offline storage familiarity native build tool like xcode gradle state management library react like redux added advantage good sense design animation micro interaction plus kindly revert updated cv acknowledge note please apply job travel till bhayander want central harbour line candidate please waste time well time appply travel till bhayander contract length month application deadline expected start date job type full time temporary walk salary per month experience flutter year preferred react native year required react j year required total work year required apis development year required application question located mention station name programming language needed html required cs required javascript required java required php required work remotely'

In [54]:
df["skills"].apply(len).value_counts().sort_index()

skills
0     182
1     221
2     284
3     359
4     304
5     302
6     195
7     163
8     105
9      69
10     36
11     25
12     10
13      9
14      6
15      2
16      5
Name: count, dtype: int64

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
tfidf = TfidfVectorizer(
    max_features=5000
)

In [57]:
tfidf_matrix = tfidf.fit_transform(
    df["processed_text"]
)

In [58]:
print(tfidf_matrix.shape)

(2277, 5000)

In [59]:
len(tfidf.get_feature_names_out())

5000

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
def recommend_jobs(user_input, top_n=5):

    user_vector = tfidf.transform([user_input.lower()])

    similarities = cosine_similarity(
        user_vector,
        tfidf_matrix
    ).flatten()

    df_temp = df.copy()

    df_temp["score"] = similarities

    df_temp = df_temp.sort_values(
        by="score",
        ascending=False
    )

    df_temp = df_temp.drop_duplicates(
        subset="Job Title"
    )

    return df_temp[
        ["Job Title", "skills", "score"]
    ].head(top_n)

In [66]:
recommend_jobs(
    "python sql machine learning pandas"
)

,Job Title,skills,score
1760,Machine Learning,"[python, machine learning, deep learning, nlp,...",0.551509
360,Django Developer,"[python, django, machine learning, deep learni...",0.225103
1938,Database Administrator,[sql],0.188860
2042,Software Engineer,"[python, machine learning, deep learning, tens...",0.182517
466,Backend Developer,"[python, sql, postgresql, django, flask, data ...",0.166732

In [67]:
recommend_jobs(
    "html css javascript react"
)

,Job Title,skills,score
642,JavaScript Developer,"[javascript, react]",0.336563
45,Flutter Developer,"[java, html, javascript, react, flutter, php]",0.316913
2024,Node js developer,"[javascript, react]",0.311452
1466,Software Engineer,"[html, javascript, microservices]",0.253543
118,Backend Developer,"[mysql, mongodb, html, javascript, react, angu...",0.240319

In [68]:
recommend_jobs(
    "flutter dart firebase android"
)

              Job Title                                      skills     score
655   Flutter Developer   [react, flutter, dart, android, firebase]  0.539375
861   Node js developer                              [git, android]  0.244285
1782  Backend Developer                        [java, git, android]  0.201304
910      Java Developer                             [java, android]  0.198657
919       iOS Developer  [javascript, react, flutter, android, ios]  0.180546

In [94]:
skill_priority = [
    "python",
    "sql",
    "statistics",
    "pandas",
    "numpy",
    "scikit learn",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "nlp",
    "aws",
    "django",
    "react",
    "flutter"
]

In [117]:
def find_skill_gap(user_skills, required_skills):

    user_skills = {
        skill.strip().lower()
        for skill in user_skills
    }

    required_skills = {
        skill.strip().lower()
        for skill in required_skills
    }

    missing = list(required_skills - user_skills)

    return sorted(missing)

In [129]:
def generate_roadmap(missing_skills):

    beginner_skills = [
        "python",
        "sql",
        "statistics",
        "pandas",
        "numpy",
        "excel",
        "git"
    ]

    intermediate_skills = [
        "scikit learn",
        "machine learning",
        "django",
        "flask",
        "react",
        "angular",
        "nodejs",
        "flutter",
        "android",
        "ios",
        "firebase",
        "mongodb",
        "mysql",
        "postgresql"
    ]

    advanced_skills = [
        "deep learning",
        "tensorflow",
        "pytorch",
        "nlp",
        "aws",
        "azure",
        "docker",
        "kubernetes",
        "spark",
        "hadoop",
        "microservices"
    ]

    roadmap = {
        "Beginner": {
            "duration": "1-2 Months",
            "skills": []
        },
        "Intermediate": {
            "duration": "2-4 Months",
            "skills": []
        },
        "Advanced": {
            "duration": "4-6 Months",
            "skills": []
        }
    }

    for skill in missing_skills:

        if skill in beginner_skills:

            roadmap["Beginner"]["skills"].append(
                skill
            )

        elif skill in intermediate_skills:

            roadmap["Intermediate"]["skills"].append(
                skill
            )

        elif skill in advanced_skills:

            roadmap["Advanced"]["skills"].append(
                skill
            )

        else:

            roadmap["Intermediate"]["skills"].append(
                skill
            )

    return roadmap

In [119]:
user_skills = [
    "python",
    "sql"
]

recommended_skills = [
    "python",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pandas"
]

gap = find_skill_gap(
    user_skills,
    recommended_skills
)

print(gap)

print(
    generate_roadmap(gap)
)

['deep learning', 'machine learning', 'pandas', 'tensorflow']
{'Month 1': 'pandas', 'Month 2': 'machine learning', 'Month 3': 'deep learning', 'Month 4': 'tensorflow'}

In [130]:
def career_roadmap(user_input, user_skills):

    recommendations = recommend_jobs(
        user_input,
        top_n=1
    )

    job_title = recommendations.iloc[0]["Job Title"]

    required_skills = recommendations.iloc[0]["skills"]

    missing_skills = find_skill_gap(
        user_skills,
        required_skills
    )

    roadmap = generate_roadmap(
        missing_skills
)

    courses = recommend_courses(
        missing_skills
    )

    return {
        "recommended_job": job_title,
        "required_skills": required_skills,
        "missing_skills": missing_skills,
        "roadmap": roadmap,
        "recommended_courses": courses
    }

In [131]:
career_roadmap(
    user_input="python sql machine learning pandas",
    user_skills=["python", "sql"]
)

{'recommended_job': 'Machine Learning',
 'required_skills': ['python',
  'machine learning',
  'deep learning',
  'nlp',
  'tensorflow',
  'pytorch',
  'scikit learn'],
 'missing_skills': ['deep learning',
  'machine learning',
  'nlp',
  'pytorch',
  'scikit learn',
  'tensorflow'],
 'roadmap': {'Beginner': {'duration': '1-2 Months', 'skills': []},
  'Intermediate': {'duration': '2-4 Months',
   'skills': ['machine learning', 'scikit learn']},
  'Advanced': {'duration': '4-6 Months',
   'skills': ['deep learning', 'nlp', 'pytorch', 'tensorflow']}},
 'recommended_courses': {'deep learning': 'Deep Learning Specialization',
  'machine learning': 'Machine Learning Specialization',
  'nlp': 'Natural Language Processing Specialization',
  'pytorch': 'PyTorch for Deep Learning',
  'scikit learn': 'Scikit-Learn for Machine Learning',
  'tensorflow': 'TensorFlow Developer Certificate'}}

In [132]:
course_map = {
    "python": "Python for Everybody",
    "sql": "SQL for Data Science",
    "pandas": "Data Analysis with Pandas",
    "numpy": "NumPy Fundamentals",
    "statistics": "Statistics for Data Science",
    "machine learning": "Machine Learning Specialization",
    "deep learning": "Deep Learning Specialization",
    "tensorflow": "TensorFlow Developer Certificate",
    "pytorch": "PyTorch for Deep Learning",
    "nlp": "Natural Language Processing Specialization",
    "django": "Django for Beginners",
    "react": "React Complete Guide",
    "flutter": "Flutter & Dart Complete Course",
    "aws": "AWS Cloud Practitioner",
    "docker": "Docker Essentials",
    "kubernetes": "Kubernetes Fundamentals",
    "scikit learn": "Scikit-Learn for Machine Learning"
}

In [133]:
def recommend_courses(missing_skills):

    recommendations = {}

    for skill in missing_skills:

        if skill in course_map:
            recommendations[skill] = course_map[skill]

    return recommendations

In [134]:
missing_skills = [
    'machine learning',
    'deep learning',
    'scikit learn',
    'tensorflow',
    'pytorch',
    'nlp'
]

In [135]:
recommend_courses(missing_skills)

{'machine learning': 'Machine Learning Specialization',
 'deep learning': 'Deep Learning Specialization',
 'scikit learn': 'Scikit-Learn for Machine Learning',
 'tensorflow': 'TensorFlow Developer Certificate',
 'pytorch': 'PyTorch for Deep Learning',
 'nlp': 'Natural Language Processing Specialization'}

In [136]:
import os

print(os.listdir())

['jobs.pkl', 'main.ipynb', 'tfidf.pkl', 'matrix.pkl', 'career_agent.ipynb', '.ipynb_checkpoints']

In [137]:
import pickle

tfidf_loaded = pickle.load(open("tfidf.pkl", "rb"))
matrix_loaded = pickle.load(open("matrix.pkl", "rb"))
jobs_loaded = pickle.load(open("jobs.pkl", "rb"))

print(type(tfidf_loaded))
print(matrix_loaded.shape)
print(jobs_loaded.shape)

<class 'sklearn.feature_extraction.text.TfidfVectorizer'>
(2277, 5000)
(2277, 6)

In [138]:
jobs_loaded.columns

Index(['Job Title', 'Job Description', 'clean_text', 'processed_text',
       'skills', 'combined_text'],
      dtype='object')